import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { GoogleOAuthProvider } from '@react-oauth/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clientid = process.env.NEXT_PUBLIC_CLIENT_ID ?? "";

  return (
    <html lang="en">
      <body className={inter.className}><GoogleOAuthProvider clientId={clientid}>{children}</GoogleOAuthProvider></body>
    </html>
  );
}
